hdfc_policy = [
    "ABCD Chronic Care Policy",
    "Arogya Sanjeevani Policy Group",
    "Arogya Sanjeevani Policy Retail",
    "Card Sure Package Insurance",
    "Critical Advantage Rider",
    "Critical Illness Policy",
    "Dengue CIS",
    "Group Health Insurance",
    "Group Mediclaim Insurance",
    "HDFC Ergo Secure 4-in-1",
    "HDFC Group Health Insurance",
    "Home Credit Assure",
    "Hospital Cash (Sep 2021)",
    "Hospital Daily Cash",
    "IPA Rider",
    "Janata Personal Accident CIS",
    "Limitless",
    "Mosquito Disease Protection Policy Group",
    "MyHealth Critical Illness",
    "MyHealth Suraksha Hospital Cash Add-on",
    "Optima Restore (Revision)",
    "Optima Secure (Revision)",
    "Optima Wellbeing (Add-on)",
    "Parenthood",
    "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
    "Protector Rider (Sep 2021)",
    "Saral Bima Suraksha",
    "Sarv Suraksha Plus Group",
    "Surrogacy and Oocyte Protect",
    "Unlimited Restore (Add-on)",
    "HDFC Home Insurance",
    "Home Credit Assure (Brochure)",
    "Home Shield (Brochure CTC)",
    "EMI Protector Plus PCV Annual",
    "EMI Protector Plus PC Annual",
    "EMI Protector Plus PC Bundled",
    "EMI Protector Plus PC SAOD",
    "EV Motor Add-ons Private Car Annual",
    "EV Motor Add-ons Private Car Bundled",
    "EV Motor Add-ons Private Car SAOD",
    "EV Motor Add-ons Two Wheeler Annual",
    "EV Motor Add-ons Two Wheeler Bundled",
    "EV Motor Add-ons Two Wheeler SAOD",
    "Motor Insurance Pricing Revision (Private Cars)",
    "Return to Invoice PC Annual",
    "Return to Invoice PC Bundled",
    "Return to Invoice PC SAOD",
    "Return to Invoice PCV Annual",
    "Standalone Third Party Long Term Two Wheeler Insurance Policy",
    "Toyota Add-on Covers PCV",
    "Toyota Add-on Covers Private Car",
    "Beyond Borders",
    "Griha Brochure (UID 7869)",
    "Group Travel Insurance",
    "HDFC Ergo Explorer",
    "Student Suraksha Overseas Travel FAQ",
    "Student Travel HDFC",
    "Travel Insurance",
    "Travelsure (Group)",
    "TravelX"
]
